import Foundation

/// Таблица строк интерфейса. Ключ → язык → текст. Английский используется как запасной.
enum Strings {
    static let table: [String: [String: String]] = interface.merging(settingsAndErrors) { a, _ in a }

    private static let interface: [String: [String: String]] = [

    "app.title": ["en": "Claude limits", "ru": "Лимиты Claude", "de": "Claude-Limits", "fr": "Limites Claude", "es": "Límites de Claude", "it": "Limiti di Claude", "pt": "Limites do Claude", "ar": "حدود Claude", "ko": "Claude 사용량", "kk": "Claude лимиттері", "ky": "Claude лимиттери", "uz": "Claude limitlari"],

    "label.session": ["en": "Session · 5 hours", "ru": "Сессия · 5 часов", "de": "Sitzung · 5 Stunden", "fr": "Session · 5 heures", "es": "Sesión · 5 horas", "it": "Sessione · 5 ore", "pt": "Sessão · 5 horas", "ar": "الجلسة · ٥ ساعات", "ko": "세션 · 5시간", "kk": "Сессия · 5 сағат", "ky": "Сессия · 5 саат", "uz": "Sessiya · 5 soat"],

    "label.week": ["en": "Week · all models", "ru": "Неделя · все модели", "de": "Woche · alle Modelle", "fr": "Semaine · tous les modèles", "es": "Semana · todos los modelos", "it": "Settimana · tutti i modelli", "pt": "Semana · todos os modelos", "ar": "الأسبوع · كل النماذج", "ko": "주간 · 전체 모델", "kk": "Апта · барлық модельдер", "ky": "Жума · бардык моделдер", "uz": "Hafta · barcha modellar"],

    "label.opus": ["en": "Week · Opus", "ru": "Неделя · Opus", "de": "Woche · Opus", "fr": "Semaine · Opus", "es": "Semana · Opus", "it": "Settimana · Opus", "pt": "Semana · Opus", "ar": "الأسبوع · Opus", "ko": "주간 · Opus", "kk": "Апта · Opus", "ky": "Жума · Opus", "uz": "Hafta · Opus"],

    "label.extra": ["en": "Extra credits", "ru": "Доп. кредиты", "de": "Zusatzguthaben", "fr": "Crédits supplém.", "es": "Créditos extra", "it": "Crediti extra", "pt": "Créditos extras", "ar": "رصيد إضافي", "ko": "추가 크레딧", "kk": "Қосымша несие", "ky": "Кошумча кредит", "uz": "Qoʻshimcha kredit"],

    "state.used": ["en": "used", "ru": "использовано", "de": "verbraucht", "fr": "utilisé", "es": "usado", "it": "usato", "pt": "usado", "ar": "مُستهلك", "ko": "사용됨", "kk": "пайдаланылды", "ky": "колдонулду", "uz": "ishlatilgan"],

    "state.exhausted": ["en": "exhausted", "ru": "исчерпано", "de": "aufgebraucht", "fr": "épuisé", "es": "agotado", "it": "esaurito", "pt": "esgotado", "ar": "نفد", "ko": "소진됨", "kk": "таусылды", "ky": "түгөндү", "uz": "tugadi"],

    "state.remaining": ["en": "%@ left", "ru": "осталось %@", "de": "noch %@", "fr": "reste %@", "es": "quedan %@", "it": "restano %@", "pt": "faltam %@", "ar": "متبقٍ %@", "ko": "%@ 남음", "kk": "%@ қалды", "ky": "%@ калды", "uz": "%@ qoldi"],

    "state.reset": ["en": "resets %@", "ru": "сброс %@", "de": "Reset %@", "fr": "réinit. %@", "es": "reinicio %@", "it": "reset %@", "pt": "renova %@", "ar": "التجديد %@", "ko": "초기화 %@", "kk": "жаңару %@", "ky": "жаңылоо %@", "uz": "yangilanish %@"],

    "state.loading": ["en": "Loading limits…", "ru": "Загружаем лимиты…", "de": "Limits werden geladen…", "fr": "Chargement des limites…", "es": "Cargando límites…", "it": "Caricamento limiti…", "pt": "Carregando limites…", "ar": "جارٍ تحميل الحدود…", "ko": "사용량 불러오는 중…", "kk": "Лимиттер жүктелуде…", "ky": "Лимиттер жүктөлүүдө…", "uz": "Limitlar yuklanmoqda…"],

    "state.noData": ["en": "No data", "ru": "Нет данных", "de": "Keine Daten", "fr": "Aucune donnée", "es": "Sin datos", "it": "Nessun dato", "pt": "Sem dados", "ar": "لا توجد بيانات", "ko": "데이터 없음", "kk": "Дерек жоқ", "ky": "Маалымат жок", "uz": "Maʼlumot yoʻq"],

    "updated.now": ["en": "Updated just now", "ru": "Обновлено только что", "de": "Gerade aktualisiert", "fr": "Mis à jour à l’instant", "es": "Actualizado ahora", "it": "Aggiornato ora", "pt": "Atualizado agora", "ar": "حُدِّث للتو", "ko": "방금 업데이트됨", "kk": "Жаңа ғана жаңартылды", "ky": "Азыр эле жаңыланды", "uz": "Hozirgina yangilandi"],

    "updated.at": ["en": "Updated at %@", "ru": "Обновлено в %@", "de": "Aktualisiert um %@", "fr": "Mis à jour à %@", "es": "Actualizado a las %@", "it": "Aggiornato alle %@", "pt": "Atualizado às %@", "ar": "حُدِّث في %@", "ko": "%@에 업데이트됨", "kk": "%@-де жаңартылды", "ky": "%@-да жаңыланды", "uz": "%@ da yangilandi"],

    "btn.refresh": ["en": "Refresh now", "ru": "Обновить сейчас", "de": "Jetzt aktualisieren", "fr": "Actualiser", "es": "Actualizar ahora", "it": "Aggiorna ora", "pt": "Atualizar agora", "ar": "تحديث الآن", "ko": "지금 새로고침", "kk": "Қазір жаңарту", "ky": "Азыр жаңылоо", "uz": "Hozir yangilash"],

    "btn.settings": ["en": "Settings", "ru": "Настройки", "de": "Einstellungen", "fr": "Réglages", "es": "Ajustes", "it": "Impostazioni", "pt": "Ajustes", "ar": "الإعدادات", "ko": "설정", "kk": "Баптаулар", "ky": "Жөндөөлөр", "uz": "Sozlamalar"],

    "btn.settingsDots": ["en": "Settings…", "ru": "Настройки…", "de": "Einstellungen…", "fr": "Réglages…", "es": "Ajustes…", "it": "Impostazioni…", "pt": "Ajustes…", "ar": "الإعدادات…", "ko": "설정…", "kk": "Баптаулар…", "ky": "Жөндөөлөр…", "uz": "Sozlamalar…"],

    "btn.quit": ["en": "Quit", "ru": "Выйти", "de": "Beenden", "fr": "Quitter", "es": "Salir", "it": "Esci", "pt": "Sair", "ar": "إنهاء", "ko": "종료", "kk": "Шығу", "ky": "Чыгуу", "uz": "Chiqish"],

    "btn.retry": ["en": "Try again", "ru": "Повторить попытку", "de": "Erneut versuchen", "fr": "Réessayer", "es": "Reintentar", "it": "Riprova", "pt": "Tentar de novo", "ar": "إعادة المحاولة", "ko": "다시 시도", "kk": "Қайталау", "ky": "Кайталоо", "uz": "Qayta urinish"],

    "pace.rate": ["en": "≈%@/day", "ru": "темп ~%@/день", "de": "≈%@/Tag", "fr": "≈%@/jour", "es": "≈%@/día", "it": "≈%@/giorno", "pt": "≈%@/dia", "ar": "≈%@/يوم", "ko": "하루 ≈%@", "kk": "≈%@/күн", "ky": "≈%@/күн", "uz": "≈%@/kun"],

    "pace.forecast": ["en": "%1$@ · about %2$@ by reset", "ru": "%1$@ · прогноз к сбросу ≈ %2$@", "de": "%1$@ · etwa %2$@ bis zum Reset", "fr": "%1$@ · env. %2$@ à la réinit.", "es": "%1$@ · ≈%2$@ al reinicio", "it": "%1$@ · circa %2$@ al reset", "pt": "%1$@ · ≈%2$@ na renovação", "ar": "%1$@ · نحو %2$@ عند التجديد", "ko": "%1$@ · 초기화 시점 약 %2$@", "kk": "%1$@ · жаңаруға дейін ≈%2$@", "ky": "%1$@ · жаңылоого чейин ≈%2$@", "uz": "%1$@ · yangilanishga ≈%2$@"],

    "pace.runout": ["en": "%1$@ · quota runs out %2$@", "ru": "%1$@ · при нём квота кончится %2$@", "de": "%1$@ · Kontingent endet %2$@", "fr": "%1$@ · quota épuisé %2$@", "es": "%1$@ · la cuota se agota %2$@", "it": "%1$@ · quota esaurita %2$@", "pt": "%1$@ · cota acaba %2$@", "ar": "%1$@ · تنفد الحصة %2$@", "ko": "%1$@ · %2$@에 소진 예상", "kk": "%1$@ · квота %2$@ таусылады", "ky": "%1$@ · квота %2$@ түгөнөт", "uz": "%1$@ · kvota %2$@ tugaydi"],




    "time.day": ["en": "d", "ru": "д", "de": "T", "fr": "j", "es": "d", "it": "g", "pt": "d", "ar": "ي", "ko": "일", "kk": "к", "ky": "к", "uz": "k"],
    "time.hour": ["en": "h", "ru": "ч", "de": "Std", "fr": "h", "es": "h", "it": "h", "pt": "h", "ar": "س", "ko": "시간", "kk": "сағ", "ky": "саат", "uz": "soat"],
    "time.min": ["en": "min", "ru": "мин", "de": "Min", "fr": "min", "es": "min", "it": "min", "pt": "min", "ar": "د", "ko": "분", "kk": "мин", "ky": "мүн", "uz": "daq"],

    "date.today": ["en": "today at %@", "ru": "сегодня в %@", "de": "heute um %@", "fr": "aujourd’hui à %@", "es": "hoy a las %@", "it": "oggi alle %@", "pt": "hoje às %@", "ar": "اليوم %@", "ko": "오늘 %@", "kk": "бүгін %@", "ky": "бүгүн %@", "uz": "bugun %@"],

    "date.tomorrow": ["en": "tomorrow at %@", "ru": "завтра в %@", "de": "morgen um %@", "fr": "demain à %@", "es": "mañana a las %@", "it": "domani alle %@", "pt": "amanhã às %@", "ar": "غدًا %@", "ko": "내일 %@", "kk": "ертең %@", "ky": "эртең %@", "uz": "ertaga %@"],

    "date.at": ["en": "%1$@ at %2$@", "ru": "%1$@ в %2$@", "de": "%1$@ um %2$@", "fr": "%1$@ à %2$@", "es": "%1$@ a las %2$@", "it": "%1$@ alle %2$@", "pt": "%1$@ às %2$@", "ar": "%1$@ %2$@", "ko": "%1$@ %2$@", "kk": "%1$@ %2$@", "ky": "%1$@ %2$@", "uz": "%1$@ %2$@"],

    "tip.session": ["en": "Session: %1$@ · resets %2$@", "ru": "Сессия: %1$@ · сброс %2$@", "de": "Sitzung: %1$@ · Reset %2$@", "fr": "Session : %1$@ · réinit. %2$@", "es": "Sesión: %1$@ · reinicio %2$@", "it": "Sessione: %1$@ · reset %2$@", "pt": "Sessão: %1$@ · renova %2$@", "ar": "الجلسة: %1$@ · التجديد %2$@", "ko": "세션: %1$@ · 초기화 %2$@", "kk": "Сессия: %1$@ · жаңару %2$@", "ky": "Сессия: %1$@ · жаңылоо %2$@", "uz": "Sessiya: %1$@ · yangilanish %2$@"],

    "tip.week": ["en": "Week: %1$@ · resets %2$@", "ru": "Неделя: %1$@ · сброс %2$@", "de": "Woche: %1$@ · Reset %2$@", "fr": "Semaine : %1$@ · réinit. %2$@", "es": "Semana: %1$@ · reinicio %2$@", "it": "Settimana: %1$@ · reset %2$@", "pt": "Semana: %1$@ · renova %2$@", "ar": "الأسبوع: %1$@ · التجديد %2$@", "ko": "주간: %1$@ · 초기화 %2$@", "kk": "Апта: %1$@ · жаңару %2$@", "ky": "Жума: %1$@ · жаңылоо %2$@", "uz": "Hafta: %1$@ · yangilanish %2$@"],

    "tip.updated": ["en": "Updated %@", "ru": "Обновлено %@", "de": "Aktualisiert %@", "fr": "Mis à jour %@", "es": "Actualizado %@", "it": "Aggiornato %@", "pt": "Atualizado %@", "ar": "حُدِّث %@", "ko": "%@ 업데이트", "kk": "%@ жаңартылды", "ky": "%@ жаңыланды", "uz": "%@ yangilandi"],

    "tip.loading": ["en": "Loading Claude limits…", "ru": "Загрузка лимитов Claude…", "de": "Claude-Limits werden geladen…", "fr": "Chargement des limites Claude…", "es": "Cargando límites de Claude…", "it": "Caricamento limiti Claude…", "pt": "Carregando limites do Claude…", "ar": "جارٍ تحميل حدود Claude…", "ko": "Claude 사용량 불러오는 중…", "kk": "Claude лимиттері жүктелуде…", "ky": "Claude лимиттери жүктөлүүдө…", "uz": "Claude limitlari yuklanmoqda…"],

    "notif.sessionTitle": ["en": "Session almost used up: %@", "ru": "Сессия почти исчерпана: %@", "de": "Sitzung fast aufgebraucht: %@", "fr": "Session presque épuisée : %@", "es": "Sesión casi agotada: %@", "it": "Sessione quasi esaurita: %@", "pt": "Sessão quase esgotada: %@", "ar": "الجلسة على وشك النفاد: %@", "ko": "세션 거의 소진: %@", "kk": "Сессия таусылуға жақын: %@", "ky": "Сессия түгөнүүгө жакын: %@", "uz": "Sessiya deyarli tugadi: %@"],

    "notif.sessionBody": ["en": "Resets %1$@. Weekly quota — %2$@.", "ru": "Сброс %1$@. Недельная квота — %2$@.", "de": "Reset %1$@. Wochenkontingent — %2$@.", "fr": "Réinit. %1$@. Quota hebdo — %2$@.", "es": "Reinicio %1$@. Cuota semanal — %2$@.", "it": "Reset %1$@. Quota settimanale — %2$@.", "pt": "Renova %1$@. Cota semanal — %2$@.", "ar": "التجديد %1$@. الحصة الأسبوعية — %2$@.", "ko": "초기화 %1$@. 주간 할당량 — %2$@.", "kk": "Жаңару %1$@. Апталық квота — %2$@.", "ky": "Жаңылоо %1$@. Жумалык квота — %2$@.", "uz": "Yangilanish %1$@. Haftalik kvota — %2$@."],

    "notif.weekTitle": ["en": "Weekly quota: %@", "ru": "Недельная квота: %@", "de": "Wochenkontingent: %@", "fr": "Quota hebdomadaire : %@", "es": "Cuota semanal: %@", "it": "Quota settimanale: %@", "pt": "Cota semanal: %@", "ar": "الحصة الأسبوعية: %@", "ko": "주간 할당량: %@", "kk": "Апталық квота: %@", "ky": "Жумалык квота: %@", "uz": "Haftalik kvota: %@"],

    "notif.weekBody": ["en": "Resets %@.", "ru": "Сброс %@.", "de": "Reset %@.", "fr": "Réinit. %@.", "es": "Reinicio %@.", "it": "Reset %@.", "pt": "Renova %@.", "ar": "التجديد %@.", "ko": "초기화 %@.", "kk": "Жаңару %@.", "ky": "Жаңылоо %@.", "uz": "Yangilanish %@."],
    ]

    private static let settingsAndErrors: [String: [String: String]] = [

    "err.rateLimited": ["en": "Too many requests — retrying in %@.", "ru": "Слишком частые запросы — повторим через %@.", "de": "Zu viele Anfragen – neuer Versuch in %@.", "fr": "Trop de requêtes — nouvel essai dans %@.", "es": "Demasiadas solicitudes: reintento en %@.", "it": "Troppe richieste — riprova tra %@.", "pt": "Muitas requisições — nova tentativa em %@.", "ar": "طلبات كثيرة — إعادة المحاولة بعد %@.", "ko": "요청이 너무 잦습니다 — %@ 후 재시도.", "kk": "Сұраныс тым жиі — %@ кейін қайталаймыз.", "ky": "Суроолор өтө көп — %@ кийин кайталайбыз.", "uz": "Soʻrovlar juda tez-tez — %@ dan soʻng qayta urinamiz."],

    "refresh.30m": ["en": "30 minutes", "ru": "30 минут", "de": "30 Minuten", "fr": "30 minutes", "es": "30 minutos", "it": "30 minuti", "pt": "30 minutos", "ar": "٣٠ دقيقة", "ko": "30분", "kk": "30 минут", "ky": "30 мүнөт", "uz": "30 daqiqa"],

    "auth.section": ["en": "Authorization", "ru": "Авторизация", "de": "Autorisierung", "fr": "Autorisation", "es": "Autorización", "it": "Autorizzazione", "pt": "Autorização", "ar": "التفويض", "ko": "인증", "kk": "Авторизация", "ky": "Авторизация", "uz": "Avtorizatsiya"],

    "auth.keychain": ["en": "Claude Code keychain", "ru": "Связка ключей Claude Code", "de": "Claude-Code-Schlüsselbund", "fr": "Trousseau Claude Code", "es": "Llavero de Claude Code", "it": "Portachiavi Claude Code", "pt": "Chaves do Claude Code", "ar": "سلسلة مفاتيح Claude Code", "ko": "Claude Code 키체인", "kk": "Claude Code кілттер тізбегі", "ky": "Claude Code ачкычтары", "uz": "Claude Code kalitlari"],

    "auth.manual": ["en": "My own token", "ru": "Свой токен", "de": "Eigenes Token", "fr": "Mon jeton", "es": "Mi propio token", "it": "Token personale", "pt": "Meu próprio token", "ar": "رمز خاص بي", "ko": "직접 발급한 토큰", "kk": "Өз токенім", "ky": "Өз токеним", "uz": "Oʻz tokenim"],

    "auth.tokenPlaceholder": ["en": "Paste the token from claude setup-token", "ru": "Вставьте токен из claude setup-token", "de": "Token aus claude setup-token einfügen", "fr": "Collez le jeton de claude setup-token", "es": "Pega el token de claude setup-token", "it": "Incolla il token da claude setup-token", "pt": "Cole o token de claude setup-token", "ar": "الصق الرمز الناتج من claude setup-token", "ko": "claude setup-token 으로 발급한 토큰을 붙여넣으세요", "kk": "claude setup-token токенін қойыңыз", "ky": "claude setup-token токенин коюңуз", "uz": "claude setup-token tokenini joylashtiring"],

    "auth.save": ["en": "Save and check", "ru": "Сохранить и проверить", "de": "Speichern und prüfen", "fr": "Enregistrer et vérifier", "es": "Guardar y comprobar", "it": "Salva e verifica", "pt": "Salvar e verificar", "ar": "حفظ وتحقّق", "ko": "저장 후 확인", "kk": "Сақтау және тексеру", "ky": "Сактоо жана текшерүү", "uz": "Saqlash va tekshirish"],

    "auth.clear": ["en": "Remove token", "ru": "Удалить токен", "de": "Token entfernen", "fr": "Supprimer le jeton", "es": "Eliminar token", "it": "Rimuovi token", "pt": "Remover token", "ar": "حذف الرمز", "ko": "토큰 삭제", "kk": "Токенді өшіру", "ky": "Токенди өчүрүү", "uz": "Tokenni oʻchirish"],

    "auth.stored": ["en": "Token saved in this app’s keychain item", "ru": "Токен сохранён в собственной записи связки ключей", "de": "Token im eigenen Schlüsselbundeintrag gespeichert", "fr": "Jeton enregistré dans l’entrée de trousseau de l’app", "es": "Token guardado en el elemento de llavero de la app", "it": "Token salvato nella voce portachiavi dell’app", "pt": "Token salvo no item de chaves do app", "ar": "حُفظ الرمز في عنصر سلسلة مفاتيح التطبيق", "ko": "앱 전용 키체인 항목에 토큰이 저장됨", "kk": "Токен қосымшаның өз жазбасында сақталды", "ky": "Токен колдонмонун өз жазуусунда сакталды", "uz": "Token ilovaning oʻz yozuvida saqlandi"],


    "auth.browser": ["en": "Authorize via browser", "ru": "Авторизоваться через браузер", "de": "Im Browser autorisieren", "fr": "Autoriser via le navigateur", "es": "Autorizar en el navegador", "it": "Autorizza dal browser", "pt": "Autorizar pelo navegador", "ar": "التفويض عبر المتصفح", "ko": "브라우저로 인증", "kk": "Браузер арқылы кіру", "ky": "Браузер аркылуу кирүү", "uz": "Brauzer orqali kirish"],

    "auth.browserHint": ["en": "Opens the browser right away: sign in with the session you already have, then paste the code back here.", "ru": "Сразу открывает браузер: вход пройдёт по уже открытой сессии, останется вставить сюда код.", "de": "Öffnet das Terminal mit claude setup-token: Der Browser meldet Sie mit der bestehenden Sitzung an, die App übernimmt das Token automatisch aus der Zwischenablage.", "fr": "Ouvre le Terminal avec claude setup-token : le navigateur vous connecte avec la session existante et l’app récupère le jeton depuis le presse-papiers.", "es": "Abre Terminal con claude setup-token: el navegador inicia sesión con la sesión que ya tienes y la app toma el token del portapapeles.", "it": "Apre il Terminale con claude setup-token: il browser accede con la sessione esistente e l’app prende il token dagli appunti.", "pt": "Abre o Terminal com claude setup-token: o navegador entra com a sessão existente e o app pega o token da área de transferência.", "ar": "يفتح Terminal مع claude setup-token: يسجّل المتصفح دخولك بالجلسة الحالية، ويلتقط التطبيق الرمز من الحافظة تلقائيًا.", "ko": "claude setup-token 을 터미널에서 실행합니다. 브라우저의 기존 세션으로 로그인되며, 앱이 클립보드에서 토큰을 자동으로 가져옵니다.", "kk": "Терминалда claude setup-token ашылады: браузер бұрыннан ашық сессиямен кіргізеді, қосымша токенді алмасу буферінен өзі алады.", "ky": "Терминалда claude setup-token ачылат: браузер мурунку сессия менен киргизет, колдонмо токенди алмашуу буферинен өзү алат.", "uz": "Terminalda claude setup-token ochiladi: brauzer mavjud sessiya bilan kiritadi, ilova tokenni vaqtinchalik xotiradan oʻzi oladi."],


    "auth.done": ["en": "Token saved", "ru": "Токен сохранён", "de": "Token gespeichert", "fr": "Jeton enregistré", "es": "Token guardado", "it": "Token salvato", "pt": "Token salvo", "ar": "تم حفظ الرمز", "ko": "토큰 저장됨", "kk": "Токен сақталды", "ky": "Токен сакталды", "uz": "Token saqlandi"],


    "set.sectionAppearance": ["en": "Appearance", "ru": "Оформление", "de": "Darstellung", "fr": "Apparence", "es": "Apariencia", "it": "Aspetto", "pt": "Aparência", "ar": "المظهر", "ko": "표시", "kk": "Безендіру", "ky": "Көрүнүш", "uz": "Koʻrinish"],

    "set.sectionUpdates": ["en": "Updates", "ru": "Обновление", "de": "Aktualisierung", "fr": "Mise à jour", "es": "Actualización", "it": "Aggiornamento", "pt": "Atualização", "ar": "التحديث", "ko": "업데이트", "kk": "Жаңарту", "ky": "Жаңылоо", "uz": "Yangilash"],

    "set.sectionNotifications": ["en": "Notifications", "ru": "Уведомления", "de": "Mitteilungen", "fr": "Notifications", "es": "Notificaciones", "it": "Notifiche", "pt": "Notificações", "ar": "الإشعارات", "ko": "알림", "kk": "Хабарландырулар", "ky": "Билдирмелер", "uz": "Bildirishnomalar"],

    "set.appTheme": ["en": "Theme", "ru": "Тема оформления", "de": "Erscheinungsbild", "fr": "Thème", "es": "Tema", "it": "Tema", "pt": "Tema", "ar": "السمة", "ko": "테마", "kk": "Тақырып", "ky": "Тема", "uz": "Mavzu"],

    "appearance.system": ["en": "Match system", "ru": "Как в системе", "de": "Wie im System", "fr": "Comme le système", "es": "Como el sistema", "it": "Come il sistema", "pt": "Como o sistema", "ar": "حسب النظام", "ko": "시스템 설정", "kk": "Жүйедегідей", "ky": "Системадагыдай", "uz": "Tizimdagidek"],

    "appearance.light": ["en": "Light", "ru": "Светлая", "de": "Hell", "fr": "Clair", "es": "Claro", "it": "Chiaro", "pt": "Claro", "ar": "فاتحة", "ko": "라이트", "kk": "Ашық", "ky": "Ачык", "uz": "Yorugʻ"],

    "appearance.dark": ["en": "Dark", "ru": "Тёмная", "de": "Dunkel", "fr": "Sombre", "es": "Oscuro", "it": "Scuro", "pt": "Escuro", "ar": "داكنة", "ko": "다크", "kk": "Қараңғы", "ky": "Караңгы", "uz": "Qorongʻi"],

    "auth.source": ["en": "Source", "ru": "Источник", "de": "Quelle", "fr": "Source", "es": "Origen", "it": "Origine", "pt": "Origem", "ar": "المصدر", "ko": "소스", "kk": "Дереккөз", "ky": "Булак", "uz": "Manba"],

    "auth.keychainHint": ["en": "The token is read from the Claude Code keychain item. macOS asks for access once per build.", "ru": "Токен читается из записи Claude Code в связке ключей. macOS спрашивает доступ один раз на сборку.", "de": "Das Token wird aus dem Claude-Code-Schlüsselbundeintrag gelesen. macOS fragt einmal pro Build nach Zugriff.", "fr": "Le jeton est lu depuis l’entrée Claude Code du trousseau. macOS demande l’accès une fois par build.", "es": "El token se lee del elemento de Claude Code en el llavero. macOS pide acceso una vez por compilación.", "it": "Il token viene letto dalla voce Claude Code nel portachiavi. macOS chiede l’accesso una volta per build.", "pt": "O token é lido do item do Claude Code nas chaves. O macOS pede acesso uma vez por build.", "ar": "يُقرأ الرمز من عنصر Claude Code في سلسلة المفاتيح. يطلب macOS الإذن مرة لكل إصدار.", "ko": "토큰은 Claude Code 키체인 항목에서 읽습니다. macOS는 빌드마다 한 번 접근 권한을 묻습니다.", "kk": "Токен кілттер тізбегіндегі Claude Code жазбасынан оқылады. macOS әр жинақта бір рет рұқсат сұрайды.", "ky": "Токен ачкычтардагы Claude Code жазуусунан окулат. macOS ар бир курулушта бир жолу уруксат сурайт.", "uz": "Token kalitlar zanjiridagi Claude Code yozuvidan oʻqiladi. macOS har bir yigʻilishda bir marta ruxsat soʻraydi."],

    "auth.starting": ["en": "Starting sign-in…", "ru": "Запускаем вход…", "de": "Anmeldung wird gestartet…", "fr": "Démarrage de la connexion…", "es": "Iniciando sesión…", "it": "Avvio dell’accesso…", "pt": "Iniciando o login…", "ar": "جارٍ بدء تسجيل الدخول…", "ko": "로그인 시작 중…", "kk": "Кіру басталуда…", "ky": "Кирүү башталууда…", "uz": "Kirish boshlanmoqda…"],

    "auth.codeHint": ["en": "The browser is open. Sign in, copy the code it shows and paste it here.", "ru": "Браузер открыт. Войдите, скопируйте показанный код и вставьте его сюда.", "de": "Der Browser ist offen. Melden Sie sich an, kopieren Sie den angezeigten Code und fügen Sie ihn hier ein.", "fr": "Le navigateur est ouvert. Connectez-vous, copiez le code affiché et collez-le ici.", "es": "El navegador está abierto. Inicia sesión, copia el código mostrado y pégalo aquí.", "it": "Il browser è aperto. Accedi, copia il codice mostrato e incollalo qui.", "pt": "O navegador está aberto. Entre, copie o código exibido e cole aqui.", "ar": "المتصفح مفتوح. سجّل الدخول وانسخ الرمز المعروض والصقه هنا.", "ko": "브라우저가 열렸습니다. 로그인 후 표시된 코드를 복사해 여기에 붙여넣으세요.", "kk": "Браузер ашылды. Кіріп, көрсетілген кодты көшіріп, осында қойыңыз.", "ky": "Браузер ачылды. Кирип, көрсөтүлгөн кодду көчүрүп, бул жерге коюңуз.", "uz": "Brauzer ochildi. Kiring, koʻrsatilgan kodni nusxalab shu yerga joylashtiring."],

    "auth.codePlaceholder": ["en": "Code from the browser", "ru": "Код из браузера", "de": "Code aus dem Browser", "fr": "Code du navigateur", "es": "Código del navegador", "it": "Codice dal browser", "pt": "Código do navegador", "ar": "الرمز من المتصفح", "ko": "브라우저의 코드", "kk": "Браузердегі код", "ky": "Браузердеги код", "uz": "Brauzerdagi kod"],

    "auth.submit": ["en": "Continue", "ru": "Продолжить", "de": "Weiter", "fr": "Continuer", "es": "Continuar", "it": "Continua", "pt": "Continuar", "ar": "متابعة", "ko": "계속", "kk": "Жалғастыру", "ky": "Улантуу", "uz": "Davom etish"],

    "auth.openAgain": ["en": "Open again", "ru": "Открыть снова", "de": "Erneut öffnen", "fr": "Rouvrir", "es": "Abrir de nuevo", "it": "Riapri", "pt": "Abrir de novo", "ar": "فتح مجددًا", "ko": "다시 열기", "kk": "Қайта ашу", "ky": "Кайра ачуу", "uz": "Qayta ochish"],

    "auth.copyLink": ["en": "Copy link", "ru": "Скопировать ссылку", "de": "Link kopieren", "fr": "Copier le lien", "es": "Copiar enlace", "it": "Copia link", "pt": "Copiar link", "ar": "نسخ الرابط", "ko": "링크 복사", "kk": "Сілтемені көшіру", "ky": "Шилтемени көчүрүү", "uz": "Havolani nusxalash"],

    "auth.cancel": ["en": "Cancel", "ru": "Отменить", "de": "Abbrechen", "fr": "Annuler", "es": "Cancelar", "it": "Annulla", "pt": "Cancelar", "ar": "إلغاء", "ko": "취소", "kk": "Болдырмау", "ky": "Жокко чыгаруу", "uz": "Bekor qilish"],

    "auth.manualEntry": ["en": "Paste a token manually", "ru": "Вставить токен вручную", "de": "Token manuell einfügen", "fr": "Coller un jeton manuellement", "es": "Pegar un token manualmente", "it": "Incolla un token manualmente", "pt": "Colar um token manualmente", "ar": "لصق الرمز يدويًا", "ko": "토큰 직접 붙여넣기", "kk": "Токенді қолмен қою", "ky": "Токенди колго коюу", "uz": "Tokenni qoʻlda joylash"],

    "auth.timeout": ["en": "Sign-in timed out.", "ru": "Время ожидания входа истекло.", "de": "Zeitüberschreitung bei der Anmeldung.", "fr": "Délai de connexion dépassé.", "es": "Se agotó el tiempo de inicio de sesión.", "it": "Tempo di accesso scaduto.", "pt": "Tempo de login esgotado.", "ar": "انتهت مهلة تسجيل الدخول.", "ko": "로그인 시간이 초과되었습니다.", "kk": "Кіру уақыты бітті.", "ky": "Кирүү убактысы бүттү.", "uz": "Kirish vaqti tugadi."],

    "auth.noToken": ["en": "Sign-in finished without a token. Check that the claude command is installed.", "ru": "Вход завершился без токена. Проверьте, что команда claude установлена.", "de": "Anmeldung ohne Token beendet. Prüfen Sie, ob der Befehl claude installiert ist.", "fr": "Connexion terminée sans jeton. Vérifiez que la commande claude est installée.", "es": "El inicio de sesión terminó sin token. Comprueba que el comando claude esté instalado.", "it": "Accesso terminato senza token. Verifica che il comando claude sia installato.", "pt": "O login terminou sem token. Verifique se o comando claude está instalado.", "ar": "انتهى تسجيل الدخول بدون رمز. تأكد من تثبيت الأمر claude.", "ko": "토큰 없이 로그인이 끝났습니다. claude 명령이 설치되어 있는지 확인하세요.", "kk": "Кіру токенсіз аяқталды. claude командасы орнатылғанын тексеріңіз.", "ky": "Кирүү токенсиз аяктады. claude буйругу орнотулганын текшериңиз.", "uz": "Kirish tokensiz yakunlandi. claude buyrugʻi oʻrnatilganini tekshiring."],

    "set.sectionSystem": ["en": "System", "ru": "Система", "de": "System", "fr": "Système", "es": "Sistema", "it": "Sistema", "pt": "Sistema", "ar": "النظام", "ko": "시스템", "kk": "Жүйе", "ky": "Система", "uz": "Tizim"],

    "err.rateLimitedGeneric": ["en": "Too many requests — waiting before the next try.", "ru": "Слишком частые запросы — ждём перед следующей попыткой.", "de": "Zu viele Anfragen – wir warten vor dem nächsten Versuch.", "fr": "Trop de requêtes — attente avant le prochain essai.", "es": "Demasiadas solicitudes: esperando antes del próximo intento.", "it": "Troppe richieste — attesa prima del prossimo tentativo.", "pt": "Muitas requisições — aguardando antes da próxima tentativa.", "ar": "طلبات كثيرة — ننتظر قبل المحاولة التالية.", "ko": "요청이 너무 잦습니다 — 다음 시도 전 대기 중.", "kk": "Сұраныс тым жиі — келесі әрекет алдында күтудеміз.", "ky": "Суроолор өтө көп — кийинки аракеттин алдында күтүүдөбүз.", "uz": "Soʻrovlar juda tez-tez — keyingi urinishdan oldin kutilmoqda."],


    "theme.adaptive": ["en": "Monochrome, color near limits", "ru": "Монохром, цвет у лимита", "de": "Monochrom, Farbe nahe am Limit", "fr": "Monochrome, couleur près des limites", "es": "Monocromo, color cerca del límite", "it": "Monocromatico, colore vicino al limite", "pt": "Monocromático, cor perto do limite", "ar": "أحادي اللون، ملوّن قرب الحد", "ko": "단색, 한도 근처에서 컬러", "kk": "Монохром, лимитке жақындағанда түсті", "ky": "Монохром, лимитке жакындаганда түстүү", "uz": "Monoxrom, limitga yaqin rangli"],

    "set.iconColorHint": ["en": "Affects the accent only. The icon and its label always follow the system menu bar theme.", "ru": "Влияет только на акцент. Иконка и подпись всегда следуют теме строки меню в системе.", "de": "Betrifft nur den Akzent. Symbol und Beschriftung folgen immer der Systemleiste.", "fr": "N’affecte que l’accent. L’icône et son libellé suivent toujours le thème de la barre des menus.", "es": "Solo afecta al acento. El icono y su texto siguen siempre el tema de la barra de menús.", "it": "Riguarda solo l’accento. L’icona e l’etichetta seguono sempre il tema della barra dei menu.", "pt": "Afeta apenas o destaque. O ícone e o texto seguem sempre o tema da barra de menus.", "ar": "يؤثر على اللون المميّز فقط. تتبع الأيقونة ونصّها سمة شريط القوائم دائمًا.", "ko": "강조 색에만 적용됩니다. 아이콘과 라벨은 항상 시스템 메뉴 막대 테마를 따릅니다.", "kk": "Тек акцентке әсер етеді. Белгіше мен жазу әрқашан жүйе мәзір жолағының тақырыбын ұстанады.", "ky": "Акцентке гана таасир этет. Белги жана жазуу дайыма системанын меню тилкесинин темасын карманат.", "uz": "Faqat aksentga taʼsir qiladi. Belgi va yozuv doim tizim menyu satri mavzusiga ergashadi."],

    "auth.rejectedFallback": ["en": "Your token has no access to usage limits — falling back to the Claude Code keychain.", "ru": "Свой токен не даёт доступа к лимитам — используем связку ключей Claude Code.", "de": "Ihr Token hat keinen Zugriff auf die Limits – es wird der Claude-Code-Schlüsselbund verwendet.", "fr": "Votre jeton n’a pas accès aux limites — retour au trousseau Claude Code.", "es": "Tu token no tiene acceso a los límites: se usa el llavero de Claude Code.", "it": "Il tuo token non ha accesso ai limiti: si usa il portachiavi di Claude Code.", "pt": "Seu token não tem acesso aos limites — usando as chaves do Claude Code.", "ar": "رمزك لا يملك صلاحية قراءة الحدود — نعود إلى سلسلة مفاتيح Claude Code.", "ko": "이 토큰에는 사용량 조회 권한이 없어 Claude Code 키체인을 사용합니다.", "kk": "Токенде лимиттерге қол жеткізу жоқ — Claude Code кілттер тізбегін қолданамыз.", "ky": "Токенде лимиттерге уруксат жок — Claude Code ачкычтарын колдонобуз.", "uz": "Tokenda limitlarga ruxsat yoʻq — Claude Code kalitlaridan foydalanamiz."],

    "err.title": ["en": "Data unavailable", "ru": "Данные недоступны", "de": "Daten nicht verfügbar", "fr": "Données indisponibles", "es": "Datos no disponibles", "it": "Dati non disponibili", "pt": "Dados indisponíveis", "ar": "البيانات غير متاحة", "ko": "데이터를 가져올 수 없음", "kk": "Дерек қолжетімсіз", "ky": "Маалымат жеткиликсиз", "uz": "Maʼlumot mavjud emas"],

    "err.hintRelogin": ["en": "Tip: open Terminal, run claude, then /login.", "ru": "Подсказка: откройте терминал, выполните claude, затем /login.", "de": "Tipp: Terminal öffnen, claude ausführen, dann /login.", "fr": "Astuce : ouvrez le Terminal, lancez claude, puis /login.", "es": "Consejo: abre Terminal, ejecuta claude y luego /login.", "it": "Suggerimento: apri Terminale, esegui claude, poi /login.", "pt": "Dica: abra o Terminal, execute claude e depois /login.", "ar": "تلميح: افتح Terminal ونفّذ claude ثم /login.", "ko": "팁: 터미널에서 claude 실행 후 /login 입력.", "kk": "Кеңес: терминалда claude, сосын /login орындаңыз.", "ky": "Кеңеш: терминалда claude, анан /login аткарыңыз.", "uz": "Maslahat: terminalda claude, soʻng /login."],

    "err.notLoggedIn": ["en": "Claude Code credentials not found. Run claude in Terminal and sign in.", "ru": "Учётные данные Claude Code не найдены. Выполните claude в терминале и войдите.", "de": "Claude-Code-Anmeldedaten nicht gefunden. Führen Sie claude im Terminal aus und melden Sie sich an.", "fr": "Identifiants Claude Code introuvables. Lancez claude dans le Terminal et connectez-vous.", "es": "No se encontraron credenciales de Claude Code. Ejecuta claude en Terminal e inicia sesión.", "it": "Credenziali di Claude Code non trovate. Esegui claude nel Terminale e accedi.", "pt": "Credenciais do Claude Code não encontradas. Execute claude no Terminal e entre.", "ar": "لم يتم العثور على بيانات اعتماد Claude Code. شغّل claude في Terminal وسجّل الدخول.", "ko": "Claude Code 자격 증명을 찾을 수 없습니다. 터미널에서 claude를 실행해 로그인하세요.", "kk": "Claude Code тіркелгі деректері табылмады. Терминалда claude орындап, кіріңіз.", "ky": "Claude Code эсептик дайындары табылган жок. Терминалда claude аткарып кириңиз.", "uz": "Claude Code hisob maʼlumotlari topilmadi. Terminalda claude ishga tushiring va kiring."],

    "err.keychainDenied": ["en": "No access to the keychain. Allow this app to read the “Claude Code-credentials” item.", "ru": "Нет доступа к связке ключей. Разрешите приложению читать запись «Claude Code-credentials».", "de": "Kein Zugriff auf den Schlüsselbund. Erlauben Sie der App, den Eintrag „Claude Code-credentials“ zu lesen.", "fr": "Pas d’accès au trousseau. Autorisez l’app à lire l’élément « Claude Code-credentials ».", "es": "Sin acceso al llavero. Permite que la app lea el elemento «Claude Code-credentials».", "it": "Nessun accesso al portachiavi. Consenti all’app di leggere la voce «Claude Code-credentials».", "pt": "Sem acesso às chaves. Permita que o app leia o item “Claude Code-credentials”.", "ar": "لا يوجد وصول إلى سلسلة المفاتيح. اسمح للتطبيق بقراءة عنصر «Claude Code-credentials».", "ko": "키체인에 접근할 수 없습니다. “Claude Code-credentials” 항목 읽기를 허용하세요.", "kk": "Кілттер тізбегіне қолжетім жоқ. «Claude Code-credentials» жазбасын оқуға рұқсат беріңіз.", "ky": "Ачкычтар тизмегине уруксат жок. «Claude Code-credentials» жазуусун окууга уруксат бериңиз.", "uz": "Kalitlar zanjiriga ruxsat yoʻq. «Claude Code-credentials» yozuvini oʻqishga ruxsat bering."],

    "err.keychainFailed": ["en": "Keychain error (%d).", "ru": "Ошибка связки ключей (%d).", "de": "Schlüsselbund-Fehler (%d).", "fr": "Erreur de trousseau (%d).", "es": "Error del llavero (%d).", "it": "Errore portachiavi (%d).", "pt": "Erro das chaves (%d).", "ar": "خطأ في سلسلة المفاتيح (%d).", "ko": "키체인 오류 (%d).", "kk": "Кілттер тізбегі қатесі (%d).", "ky": "Ачкычтар тизмеги катасы (%d).", "uz": "Kalitlar zanjiri xatosi (%d)."],

    "err.malformed": ["en": "Could not parse Claude Code credentials.", "ru": "Не удалось разобрать учётные данные Claude Code.", "de": "Anmeldedaten konnten nicht gelesen werden.", "fr": "Impossible de lire les identifiants Claude Code.", "es": "No se pudieron leer las credenciales de Claude Code.", "it": "Impossibile leggere le credenziali di Claude Code.", "pt": "Não foi possível ler as credenciais do Claude Code.", "ar": "تعذّر تحليل بيانات اعتماد Claude Code.", "ko": "Claude Code 자격 증명을 해석할 수 없습니다.", "kk": "Claude Code деректерін оқу мүмкін болмады.", "ky": "Claude Code дайындарын окуу мүмкүн болгон жок.", "uz": "Claude Code maʼlumotlarini oʻqib boʻlmadi."],

    "err.unauthorized": ["en": "Token expired. Run claude and sign in again.", "ru": "Токен устарел. Запустите claude и войдите заново.", "de": "Token abgelaufen. Starten Sie claude und melden Sie sich erneut an.", "fr": "Jeton expiré. Relancez claude et reconnectez-vous.", "es": "Token caducado. Ejecuta claude e inicia sesión de nuevo.", "it": "Token scaduto. Esegui claude e accedi di nuovo.", "pt": "Token expirado. Execute claude e entre novamente.", "ar": "انتهت صلاحية الرمز. شغّل claude وسجّل الدخول مجددًا.", "ko": "토큰이 만료되었습니다. claude를 실행해 다시 로그인하세요.", "kk": "Токен ескірді. claude іске қосып, қайта кіріңіз.", "ky": "Токен эскирди. claude ишке киргизип, кайра кириңиз.", "uz": "Token eskirdi. claude ishga tushiring va qayta kiring."],

    "err.http": ["en": "Server returned error %d.", "ru": "Сервер ответил ошибкой %d.", "de": "Server meldete Fehler %d.", "fr": "Le serveur a renvoyé l’erreur %d.", "es": "El servidor devolvió el error %d.", "it": "Il server ha restituito l’errore %d.", "pt": "O servidor retornou o erro %d.", "ar": "أعاد الخادم الخطأ %d.", "ko": "서버 오류 %d.", "kk": "Сервер %d қатесін қайтарды.", "ky": "Сервер %d катасын кайтарды.", "uz": "Server %d xatosini qaytardi."],

    "err.network": ["en": "No connection: %@", "ru": "Нет связи: %@", "de": "Keine Verbindung: %@", "fr": "Pas de connexion : %@", "es": "Sin conexión: %@", "it": "Nessuna connessione: %@", "pt": "Sem conexão: %@", "ar": "لا يوجد اتصال: %@", "ko": "연결 없음: %@", "kk": "Байланыс жоқ: %@", "ky": "Байланыш жок: %@", "uz": "Aloqa yoʻq: %@"],

    "err.badResponse": ["en": "Unexpected server response.", "ru": "Неожиданный формат ответа сервера.", "de": "Unerwartete Serverantwort.", "fr": "Réponse inattendue du serveur.", "es": "Respuesta inesperada del servidor.", "it": "Risposta del server inattesa.", "pt": "Resposta inesperada do servidor.", "ar": "استجابة غير متوقعة من الخادم.", "ko": "예상치 못한 서버 응답입니다.", "kk": "Сервердің күтпеген жауабы.", "ky": "Сервердин күтүлбөгөн жообу.", "uz": "Serverning kutilmagan javobi."],

    "set.menuBarView": ["en": "Menu bar appearance", "ru": "Вид в строке меню", "de": "Darstellung in der Menüleiste", "fr": "Apparence dans la barre des menus", "es": "Aspecto en la barra de menús", "it": "Aspetto nella barra dei menu", "pt": "Aparência na barra de menus", "ar": "المظهر في شريط القوائم", "ko": "메뉴 막대 표시", "kk": "Мәзір жолағындағы көрініс", "ky": "Меню тилкесиндеги көрүнүш", "uz": "Menyu satridagi koʻrinish"],

    "set.iconColor": ["en": "Icon color", "ru": "Цвет иконки", "de": "Symbolfarbe", "fr": "Couleur de l’icône", "es": "Color del icono", "it": "Colore dell’icona", "pt": "Cor do ícone", "ar": "لون الأيقونة", "ko": "아이콘 색상", "kk": "Белгіше түсі", "ky": "Белгинин түсү", "uz": "Belgi rangi"],

    "set.refreshRate": ["en": "Refresh interval", "ru": "Частота обновления", "de": "Aktualisierungsintervall", "fr": "Fréquence d’actualisation", "es": "Intervalo de actualización", "it": "Intervallo di aggiornamento", "pt": "Intervalo de atualização", "ar": "معدل التحديث", "ko": "새로고침 주기", "kk": "Жаңарту жиілігі", "ky": "Жаңылоо жыштыгы", "uz": "Yangilash chastotasi"],


    "set.notificationsOn": ["en": "Warn about limits", "ru": "Предупреждать о лимитах", "de": "Vor Limits warnen", "fr": "Prévenir à l’approche des limites", "es": "Avisar sobre los límites", "it": "Avvisa sui limiti", "pt": "Avisar sobre os limites", "ar": "التنبيه قبل بلوغ الحدود", "ko": "한도 도달 전 알림", "kk": "Лимиттер туралы ескерту", "ky": "Лимиттер жөнүндө эскертүү", "uz": "Limitlar haqida ogohlantirish"],

    "set.beforeReset": ["en": "Before session reset", "ru": "Перед сбросом сессии", "de": "Vor dem Sitzungs-Reset", "fr": "Avant la réinit. de session", "es": "Antes del reinicio de sesión", "it": "Prima del reset sessione", "pt": "Antes da renovação da sessão", "ar": "قبل تجديد الجلسة", "ko": "세션 초기화 전", "kk": "Сессия жаңаруы алдында", "ky": "Сессия жаңылоосу алдында", "uz": "Sessiya yangilanishidan oldin"],

    "set.sessionThreshold": ["en": "Session threshold", "ru": "Порог сессии", "de": "Sitzungsschwelle", "fr": "Seuil de session", "es": "Umbral de sesión", "it": "Soglia sessione", "pt": "Limiar da sessão", "ar": "عتبة الجلسة", "ko": "세션 임계값", "kk": "Сессия шегі", "ky": "Сессия чеги", "uz": "Sessiya chegarasi"],

    "set.weekThreshold": ["en": "Weekly threshold", "ru": "Порог недели", "de": "Wochenschwelle", "fr": "Seuil hebdomadaire", "es": "Umbral semanal", "it": "Soglia settimanale", "pt": "Limiar semanal", "ar": "العتبة الأسبوعية", "ko": "주간 임계값", "kk": "Апта шегі", "ky": "Жума чеги", "uz": "Haftalik chegara"],

    "set.thresholdValue": ["en": "%d%% used", "ru": "%d%% использовано", "de": "%d%% verbraucht", "fr": "%d%% utilisé", "es": "%d%% usado", "it": "%d%% usato", "pt": "%d%% usado", "ar": "%d%% مُستهلك", "ko": "%d%% 사용", "kk": "%d%% пайдаланылды", "ky": "%d%% колдонулду", "uz": "%d%% ishlatilgan"],




    "set.autostartOn": ["en": "Launch at login", "ru": "Запускать при входе в систему", "de": "Beim Anmelden starten", "fr": "Lancer à l’ouverture de session", "es": "Abrir al iniciar sesión", "it": "Avvia all’accesso", "pt": "Abrir ao iniciar sessão", "ar": "التشغيل عند تسجيل الدخول", "ko": "로그인 시 실행", "kk": "Жүйеге кіргенде іске қосу", "ky": "Системага киргенде жүргүзүү", "uz": "Tizimga kirganda ishga tushirish"],

    "set.language": ["en": "Language", "ru": "Язык", "de": "Sprache", "fr": "Langue", "es": "Idioma", "it": "Lingua", "pt": "Idioma", "ar": "اللغة", "ko": "언어", "kk": "Тіл", "ky": "Тил", "uz": "Til"],

    "set.languageSystem": ["en": "System language", "ru": "Как в системе", "de": "Systemsprache", "fr": "Langue du système", "es": "Idioma del sistema", "it": "Lingua di sistema", "pt": "Idioma do sistema", "ar": "لغة النظام", "ko": "시스템 언어", "kk": "Жүйедегідей", "ky": "Системадагыдай", "uz": "Tizim tili"],

    "set.privacy": ["en": "Data comes from your Claude Code account: the token is read from the keychain and the request goes straight to api.anthropic.com. Nothing is sent anywhere else.", "ru": "Данные берутся из вашей учётной записи Claude Code: токен читается из связки ключей, запрос идёт напрямую в api.anthropic.com. Никуда больше ничего не отправляется.", "de": "Die Daten stammen aus Ihrem Claude-Code-Konto: Das Token wird aus dem Schlüsselbund gelesen, die Anfrage geht direkt an api.anthropic.com. Sonst wird nichts gesendet.", "fr": "Les données proviennent de votre compte Claude Code : le jeton est lu dans le trousseau et la requête va directement à api.anthropic.com. Rien n’est envoyé ailleurs.", "es": "Los datos provienen de tu cuenta de Claude Code: el token se lee del llavero y la petición va directa a api.anthropic.com. No se envía nada a ningún otro sitio.", "it": "I dati provengono dal tuo account Claude Code: il token è letto dal portachiavi e la richiesta va direttamente ad api.anthropic.com. Nient’altro viene inviato.", "pt": "Os dados vêm da sua conta do Claude Code: o token é lido das chaves e a requisição vai direto para api.anthropic.com. Nada é enviado para outro lugar.", "ar": "تأتي البيانات من حسابك في Claude Code: يُقرأ الرمز من سلسلة المفاتيح ويذهب الطلب مباشرة إلى api.anthropic.com. ولا يُرسل أي شيء إلى جهة أخرى.", "ko": "데이터는 사용자의 Claude Code 계정에서 가져옵니다. 토큰은 키체인에서 읽고 요청은 api.anthropic.com으로 바로 전송되며, 다른 곳으로는 아무것도 보내지 않습니다.", "kk": "Дерек сіздің Claude Code тіркелгіңізден алынады: токен кілттер тізбегінен оқылады, сұраныс тікелей api.anthropic.com-ға барады. Басқа ешқайда ештеңе жіберілмейді.", "ky": "Маалымат сиздин Claude Code эсебиңизден алынат: токен ачкычтар тизмегинен окулат, суроо түз api.anthropic.com'го барат. Башка эч жакка эч нерсе жөнөтүлбөйт.", "uz": "Maʼlumot sizning Claude Code hisobingizdan olinadi: token kalitlar zanjiridan oʻqiladi, soʻrov toʻgʻridan-toʻgʻri api.anthropic.com ga boradi. Boshqa hech qayerga hech narsa yuborilmaydi."],

    "window.settings": ["en": "Claude limits — Settings", "ru": "Лимиты Claude — Настройки", "de": "Claude-Limits — Einstellungen", "fr": "Limites Claude — Réglages", "es": "Límites de Claude: ajustes", "it": "Limiti di Claude — Impostazioni", "pt": "Limites do Claude — Ajustes", "ar": "حدود Claude — الإعدادات", "ko": "Claude 사용량 — 설정", "kk": "Claude лимиттері — Баптаулар", "ky": "Claude лимиттери — Жөндөөлөр", "uz": "Claude limitlari — Sozlamalar"],

    "style.ring": ["en": "Ring", "ru": "Кольцо", "de": "Ring", "fr": "Anneau", "es": "Anillo", "it": "Anello", "pt": "Anel", "ar": "حلقة", "ko": "링", "kk": "Шеңбер", "ky": "Шакек", "uz": "Halqa"],
    "style.ringTime": ["en": "Ring + time", "ru": "Кольцо + время", "de": "Ring + Zeit", "fr": "Anneau + temps", "es": "Anillo + tiempo", "it": "Anello + tempo", "pt": "Anel + tempo", "ar": "حلقة + وقت", "ko": "링 + 시간", "kk": "Шеңбер + уақыт", "ky": "Шакек + убакыт", "uz": "Halqa + vaqt"],
    "style.ringPercents": ["en": "Ring + percent", "ru": "Кольцо + проценты", "de": "Ring + Prozent", "fr": "Anneau + %", "es": "Anillo + %", "it": "Anello + %", "pt": "Anel + %", "ar": "حلقة + نسبة", "ko": "링 + 퍼센트", "kk": "Шеңбер + пайыз", "ky": "Шакек + пайыз", "uz": "Halqa + foiz"],
    "style.ringRemaining": ["en": "Ring + left", "ru": "Кольцо + остаток", "de": "Ring + Rest", "fr": "Anneau + restant", "es": "Anillo + restante", "it": "Anello + residuo", "pt": "Anel + restante", "ar": "حلقة + المتبقي", "ko": "링 + 잔여", "kk": "Шеңбер + қалдық", "ky": "Шакек + калдык", "uz": "Halqa + qoldiq"],
    "style.bars": ["en": "Two bars", "ru": "Две полосы", "de": "Zwei Balken", "fr": "Deux barres", "es": "Dos barras", "it": "Due barre", "pt": "Duas barras", "ar": "شريطان", "ko": "막대 2개", "kk": "Екі жолақ", "ky": "Эки тилке", "uz": "Ikki chiziq"],
    "style.barsTime": ["en": "Bars + time", "ru": "Полосы + время", "de": "Balken + Zeit", "fr": "Barres + temps", "es": "Barras + tiempo", "it": "Barre + tempo", "pt": "Barras + tempo", "ar": "أشرطة + وقت", "ko": "막대 + 시간", "kk": "Жолақ + уақыт", "ky": "Тилке + убакыт", "uz": "Chiziq + vaqt"],
    "style.battery": ["en": "Battery", "ru": "Батарейка", "de": "Batterie", "fr": "Batterie", "es": "Batería", "it": "Batteria", "pt": "Bateria", "ar": "بطارية", "ko": "배터리", "kk": "Батарея", "ky": "Батарея", "uz": "Batareya"],
    "style.batteryTime": ["en": "Battery + time", "ru": "Батарейка + время", "de": "Batterie + Zeit", "fr": "Batterie + temps", "es": "Batería + tiempo", "it": "Batteria + tempo", "pt": "Bateria + tempo", "ar": "بطارية + وقت", "ko": "배터리 + 시간", "kk": "Батарея + уақыт", "ky": "Батарея + убакыт", "uz": "Batareya + vaqt"],
    "style.dots": ["en": "Dots", "ru": "Точки", "de": "Punkte", "fr": "Points", "es": "Puntos", "it": "Punti", "pt": "Pontos", "ar": "نقاط", "ko": "점", "kk": "Нүктелер", "ky": "Чекиттер", "uz": "Nuqtalar"],
    "style.text": ["en": "Text only", "ru": "Только текст", "de": "Nur Text", "fr": "Texte seul", "es": "Solo texto", "it": "Solo testo", "pt": "Só texto", "ar": "نص فقط", "ko": "텍스트만", "kk": "Тек мәтін", "ky": "Текст гана", "uz": "Faqat matn"],
    "style.textPercents": ["en": "Text · percent", "ru": "Текст · проценты", "de": "Text · Prozent", "fr": "Texte · %", "es": "Texto · %", "it": "Testo · %", "pt": "Texto · %", "ar": "نص · نسبة", "ko": "텍스트 · 퍼센트", "kk": "Мәтін · пайыз", "ky": "Текст · пайыз", "uz": "Matn · foiz"],

    "theme.system": ["en": "Match system", "ru": "Как в системе", "de": "Wie im System", "fr": "Comme le système", "es": "Como el sistema", "it": "Come il sistema", "pt": "Como o sistema", "ar": "حسب النظام", "ko": "시스템 설정", "kk": "Жүйедегідей", "ky": "Системадагыдай", "uz": "Tizimdagidek"],
    "theme.mono": ["en": "Always monochrome", "ru": "Всегда монохром", "de": "Immer monochrom", "fr": "Toujours monochrome", "es": "Siempre monocromo", "it": "Sempre monocromatico", "pt": "Sempre monocromático", "ar": "أحادي اللون دائمًا", "ko": "항상 단색", "kk": "Әрқашан монохром", "ky": "Ар дайым монохром", "uz": "Doim monoxrom"],
    "theme.colored": ["en": "Always colored", "ru": "Всегда цветная", "de": "Immer farbig", "fr": "Toujours en couleur", "es": "Siempre en color", "it": "Sempre a colori", "pt": "Sempre colorido", "ar": "ملوّن دائمًا", "ko": "항상 컬러", "kk": "Әрқашан түсті", "ky": "Ар дайым түстүү", "uz": "Doim rangli"],

    "refresh.1m": ["en": "1 minute", "ru": "1 минута", "de": "1 Minute", "fr": "1 minute", "es": "1 minuto", "it": "1 minuto", "pt": "1 minuto", "ar": "دقيقة واحدة", "ko": "1분", "kk": "1 минут", "ky": "1 мүнөт", "uz": "1 daqiqa"],

    "refresh.5m": ["en": "5 minutes", "ru": "5 минут", "de": "5 Minuten", "fr": "5 minutes", "es": "5 minutos", "it": "5 minuti", "pt": "5 minutos", "ar": "٥ دقائق", "ko": "5분", "kk": "5 минут", "ky": "5 мүнөт", "uz": "5 daqiqa"],
    "refresh.10m": ["en": "10 minutes", "ru": "10 минут", "de": "10 Minuten", "fr": "10 minutes", "es": "10 minutos", "it": "10 minuti", "pt": "10 minutos", "ar": "١٠ دقائق", "ko": "10분", "kk": "10 минут", "ky": "10 мүнөт", "uz": "10 daqiqa"],

    "refresh.15m": ["en": "15 minutes", "ru": "15 минут", "de": "15 Minuten", "fr": "15 minutes", "es": "15 minutos", "it": "15 minuti", "pt": "15 minutos", "ar": "١٥ دقيقة", "ko": "15분", "kk": "15 минут", "ky": "15 мүнөт", "uz": "15 daqiqa"],

    "warn.off": ["en": "Off", "ru": "Выключено", "de": "Aus", "fr": "Désactivé", "es": "Desactivado", "it": "Disattivato", "pt": "Desativado", "ar": "معطّل", "ko": "끔", "kk": "Өшірулі", "ky": "Өчүк", "uz": "Oʻchiq"],
    "warn.15m": ["en": "15 minutes before", "ru": "за 15 минут", "de": "15 Minuten vorher", "fr": "15 minutes avant", "es": "15 minutos antes", "it": "15 minuti prima", "pt": "15 minutos antes", "ar": "قبل ١٥ دقيقة", "ko": "15분 전", "kk": "15 минут бұрын", "ky": "15 мүнөт мурун", "uz": "15 daqiqa oldin"],
    "warn.30m": ["en": "30 minutes before", "ru": "за 30 минут", "de": "30 Minuten vorher", "fr": "30 minutes avant", "es": "30 minutos antes", "it": "30 minuti prima", "pt": "30 minutos antes", "ar": "قبل ٣٠ دقيقة", "ko": "30분 전", "kk": "30 минут бұрын", "ky": "30 мүнөт мурун", "uz": "30 daqiqa oldin"],
    "warn.1h": ["en": "1 hour before", "ru": "за час", "de": "1 Stunde vorher", "fr": "1 heure avant", "es": "1 hora antes", "it": "1 ora prima", "pt": "1 hora antes", "ar": "قبل ساعة", "ko": "1시간 전", "kk": "1 сағат бұрын", "ky": "1 саат мурун", "uz": "1 soat oldin"],
    ]
}
